name: Test Yaml
env:
  cacheId: "9"
on:
  workflow_dispatch: null
  push:
    tags:
     - '*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compile-sdk:
          - 33
        build-tools:
          - 33.0.2
        sdk-tools:
          - 4333796
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
      - name: setup ubuntu
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set latest tag
        id: latest_tag
        run: echo "latesttag=$(git describe --tags --match='v[0-9].0*' HEAD)" >> $GITHUB_OUTPUT

      #builds changelog but just fetches last commit
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # fromTag: "v1.1.1"
          fromTag: ${{ steps.latest_tag.outputs.latesttag }}
          toTag: ${{ steps.vars.outputs.tag }}
          # configuration: ".github/config/configuration.json"
          # ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}