name: Native Build & Test

env:
  cacheId: '8' # increment to expire the cache

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/legacy/app/**'
      - 'packages/legacy/core/**'
      - 'packages/oca/**'
      - '**/package-lock.json'
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main,actions]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/packages/legacy/app/Gemfile
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./packages/legacy/app

      - name: Cache pod dependencies
        id: pod-cache
        uses: actions/cache@v3
        with:
          path: packages/legacy/app/ios/Pods
          key: ${{ runner.os }}-pods-${{ env.cacheId }}-${{ hashFiles('**/Podfile.lock ') }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ env.cacheId }}-

      # Watch for changes to the `App` and `iOS` paths, use
      # git for cache keys.
      - name: Generate cache key
        run: |
          echo $(git rev-parse HEAD:packages/legacy/core/App) > ./dd-cache-key.txt
          echo $(git rev-parse HEAD:packages/legacy/app/ios) >> ./dd-cache-key.txt

      - name: Cache derived data
        uses: actions/cache@v3
        with:
          path: packages/legacy/app/ios/xbuild/Build
          key: ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-${{ hashFiles('**/dd-cache-key.txt') }}
          restore-keys: |
            ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-

      - name: Install React Native Dependencies
        run: |
          yarn install --immutable && \
          git status

      - name: Build Workspace
        run: |
          yarn lerna run build

      - name: Install iOS dependencies
        # if: steps.pod-cache.outputs.cache-hit != 'true' || steps.npm-cache.outputs.cache-hit != 'true'
        working-directory: ./packages/legacy/app/ios
        run: |
          bundle install --frozen --gemfile=${BUNDLE_GEMFILE} && \
          pod install && \
          git status && \
          git diff Podfile.lock

      - name: Run release build
        # if: steps.pod-cache.outputs.cache-hit != 'true' || steps.npm-cache.outputs.cache-hit != 'true'
        working-directory: ./packages/legacy/app/ios
        run: |
          xcodebuild \
          -workspace AriesBifold.xcworkspace \
          -scheme AriesBifold \
          -configuration Release \
          -derivedDataPath xbuild \
          build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO

      # This is a 1G file that adds little to speeding up
      # the build but does impact cache size.
      - name: Cleanup large artifacts
        working-directory: ./packages/legacy/app/ios
        run: |
          rm -rf build/Build/Products/Debug-iphoneos/AriesBifold.app
